# Form implementation generated from reading ui file '.\\templates\\dlgGestion.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_tipoprop(object):
    def setupUi(self, dlg_tipoprop):
        dlg_tipoprop.setObjectName("dlg_tipoprop")
        dlg_tipoprop.resize(400, 300)
        dlg_tipoprop.setMinimumSize(QtCore.QSize(400, 300))
        dlg_tipoprop.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/a23yelkovq/.designer/img/icono.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlg_tipoprop.setWindowIcon(icon)
        dlg_tipoprop.setModal(True)
        self.layoutWidget = QtWidgets.QWidget(parent=dlg_tipoprop)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 30, 302, 230))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.layoutWidget)
        self.frame.setMinimumSize(QtCore.QSize(300, 200))
        self.frame.setMaximumSize(QtCore.QSize(300, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 100, 280, 20))
        self.label.setMinimumSize(QtCore.QSize(280, 20))
        self.label.setMaximumSize(QtCore.QSize(280, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.txtTipoprop = QtWidgets.QLineEdit(parent=self.frame)
        self.txtTipoprop.setGeometry(QtCore.QRect(80, 130, 150, 20))
        self.txtTipoprop.setMinimumSize(QtCore.QSize(150, 20))
        self.txtTipoprop.setMaximumSize(QtCore.QSize(150, 20))
        self.txtTipoprop.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txtTipoprop.setObjectName("txtTipoprop")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 211, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\\\templates\\../img/nombre-02.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAltaTipoprop = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnAltaTipoprop.setMinimumSize(QtCore.QSize(80, 19))
        self.btnAltaTipoprop.setMaximumSize(QtCore.QSize(80, 20))
        self.btnAltaTipoprop.setObjectName("btnAltaTipoprop")
        self.horizontalLayout.addWidget(self.btnAltaTipoprop)
        self.btnDelTipoprop = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnDelTipoprop.setMinimumSize(QtCore.QSize(80, 19))
        self.btnDelTipoprop.setMaximumSize(QtCore.QSize(80, 20))
        self.btnDelTipoprop.setObjectName("btnDelTipoprop")
        self.horizontalLayout.addWidget(self.btnDelTipoprop)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(dlg_tipoprop)
        QtCore.QMetaObject.connectSlotsByName(dlg_tipoprop)

    def retranslateUi(self, dlg_tipoprop):
        _translate = QtCore.QCoreApplication.translate
        dlg_tipoprop.setWindowTitle(_translate("dlg_tipoprop", "Gestión tipo propiedades"))
        self.label.setText(_translate("dlg_tipoprop", "Introduzca tipo de propiedad a crear o eliminar"))
        self.btnAltaTipoprop.setText(_translate("dlg_tipoprop", "Alta"))
        self.btnDelTipoprop.setText(_translate("dlg_tipoprop", "Eliminar"))
