# Form implementation generated from reading ui file '.\\templates\\dlgGestion.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_tipoprop(object):
    def setupUi(self, dlg_tipoprop):
        dlg_tipoprop.setObjectName("dlg_tipoprop")
        dlg_tipoprop.resize(400, 200)
        dlg_tipoprop.setMinimumSize(QtCore.QSize(400, 200))
        dlg_tipoprop.setMaximumSize(QtCore.QSize(400, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\\\templates\\../img/icono.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlg_tipoprop.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(parent=dlg_tipoprop)
        self.widget.setGeometry(QtCore.QRect(50, 30, 302, 130))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setMinimumSize(QtCore.QSize(300, 100))
        self.frame.setMaximumSize(QtCore.QSize(300, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 280, 20))
        self.label.setMinimumSize(QtCore.QSize(280, 20))
        self.label.setMaximumSize(QtCore.QSize(280, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.txtTipoprop = QtWidgets.QLineEdit(parent=self.frame)
        self.txtTipoprop.setGeometry(QtCore.QRect(70, 60, 150, 20))
        self.txtTipoprop.setMinimumSize(QtCore.QSize(150, 20))
        self.txtTipoprop.setMaximumSize(QtCore.QSize(150, 20))
        self.txtTipoprop.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txtTipoprop.setObjectName("txtTipoprop")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAltaTipoprop = QtWidgets.QPushButton(parent=self.widget)
        self.btnAltaTipoprop.setMinimumSize(QtCore.QSize(80, 19))
        self.btnAltaTipoprop.setMaximumSize(QtCore.QSize(80, 20))
        self.btnAltaTipoprop.setObjectName("btnAltaTipoprop")
        self.horizontalLayout.addWidget(self.btnAltaTipoprop)
        self.btnDelTipoprop = QtWidgets.QPushButton(parent=self.widget)
        self.btnDelTipoprop.setMinimumSize(QtCore.QSize(80, 19))
        self.btnDelTipoprop.setMaximumSize(QtCore.QSize(80, 20))
        self.btnDelTipoprop.setObjectName("btnDelTipoprop")
        self.horizontalLayout.addWidget(self.btnDelTipoprop)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dlg_tipoprop)
        QtCore.QMetaObject.connectSlotsByName(dlg_tipoprop)

    def retranslateUi(self, dlg_tipoprop):
        _translate = QtCore.QCoreApplication.translate
        dlg_tipoprop.setWindowTitle(_translate("dlg_tipoprop", "Gestión tipo propiedades"))
        self.label.setText(_translate("dlg_tipoprop", "Introduzca tipo de propiedad a crear o eliminar"))
        self.btnAltaTipoprop.setText(_translate("dlg_tipoprop", "Alta"))
        self.btnDelTipoprop.setText(_translate("dlg_tipoprop", "Eliminar"))
